apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapi-project
  labels:
    app: app
data:
  default.conf: |
    upstream app_project {
        server app-service:8080;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://tech_challenge;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }

