apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: fastapi-project
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: deployment_app:latest
          imagePullPolicy: Always
          name: sample-container
          envFrom:
          ports:
            - containerPort: 8080
              name: app
          readinessProbe:
            httpGet:
              port: 8080
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 8080
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"

